FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"

# https://docs.influxdata.com/influxdb/v2.0/get-started/#start-with-influxdb-oss
# Download InfluxDB v2.0 
ADD			https://dl.influxdata.com/influxdb/releases/influxdb-2.0.2_linux_amd64.tar.gz .

# Unpackage contents to the current working directory
RUN			tar xvzf influxdb-2.0.2_linux_amd64.tar.gz && rm influxdb-2.0.2_linux_amd64.tar.gz 

# Alpine Linux does /bin/ash does not supprot curly barckets
# https://lists.uclibc.org/pipermail/busybox/2011-July/076255.html
# Copy the influx and influxd binary to your $PATH
RUN			mv influxdb-2.0.2_linux_amd64/influx /usr/local/bin/ && mv influxdb-2.0.2_linux_amd64/influxd /usr/local/bin/ && rm -r influxdb-2.0.2_linux_amd64/

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/influxdb/entrypoint.sh /
COPY        srcs/influxdb/telegraf.conf /etc/telegraf/telegraf.conf
#COPY        srcs/influxdb/configs /root/.influxdbv2/configs
RUN         chmod -R 775 entrypoint.sh

EXPOSE		8086
ENTRYPOINT	["./entrypoint.sh"]

# https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Upgrade_a_Running_System


# Alpine Linux packages for Telegraf and InfluxDB
# https://pkgs.alpinelinux.org/packages?name=telegraf&branch=edge&arch=x86_64
# https://pkgs.alpinelinux.org/packages?name=influx*&branch=edge&arch=x86_64

# InfluxDB Ports
# https://docs.influxdata.com/influxdb/v1.8/administration/ports/
