apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - {port: 20, name: ftps-data}
  - {port: 21, name: ftps}
  - {port: 49201, name: pavs1}
  - {port: 49202, name: pavs2}
  - {port: 49203, name: pavs3}
  - {port: 49204, name: pavs4}
  - {port: 49205, name: pavs5}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps:ft_services
        name: ftps
        imagePullPolicy: Never
#        #command: ["sh", "-c", "tail -f /dev/null"]
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 49201
        - containerPort: 49202
        - containerPort: 49203
        - containerPort: 49204
        - containerPort: 49205
        env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
