FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"
RUN			apk update && apk upgrade && apk add --no-cache mariadb mariadb-client 

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/mysql/entrypoint.sh /
COPY        srcs/mysql/telegraf.conf /etc/telegraf/telegraf.conf
RUN         chmod -R 775 entrypoint.sh

RUN         /usr/bin/mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY        srcs/mysql/db_user_create_script.sql /ft_services/mariadb/

ENTRYPOINT	["./entrypoint.sh"]

# https://wiki.alpinelinux.org/wiki/MariaDB