FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"
RUN			apk update && apk upgrade && apk add --no-cache \
            grafana \
            grafana-openrc \
            grafana-image-renderer \
            grafana-image-renderer-openrc
ENTRYPOINT	["entrypoint.sh"]