FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"

# Background on why "mkdir -p /run/nginx" is needed
# https://github.com/gliderlabs/docker-alpine/issues/185
# https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14500
RUN 		mkdir -p /run/nginx
RUN			apk update && apk upgrade && apk add --no-cache nginx nginx-openrc openssh

# https://stackoverflow.com/questions/42154249/difference-http-redirect-vs-reverse-proxy-in-nginx
EXPOSE		80 443 22

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/nginx/entrypoint.sh /
COPY        srcs/nginx/telegraf.conf /etc/telegraf/telegraf.conf
COPY        srcs/nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN         chmod -R 775 entrypoint.sh

ENTRYPOINT	["./entrypoint.sh"]