FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"

# Background on why "mkdir -p /run/nginx" is needed
# https://github.com/gliderlabs/docker-alpine/issues/185
# https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14500

RUN 		mkdir -p /run/nginx

# https://docs.phpmyadmin.net/en/latest/require.html 
# https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7-common
# https://www.php.net/manual/en/libxml.installation.php >> The libxml extension is enabled by default

RUN			apk update && apk upgrade && apk add --no-cache nginx nginx-openrc php7 php7-fpm php7-common php7-pecl-imagick phpmyadmin 
COPY        srcs/phpmyadmin/config.inc.php /etc/phpmyadmin/config.inc.php
RUN         chown nginx:nginx -R /usr/share/webapps/phpmyadmin

EXPOSE		5000

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/phpmyadmin/entrypoint.sh /
COPY        srcs/phpmyadmin/telegraf.conf /etc/telegraf/telegraf.conf
COPY        srcs/phpmyadmin/nginx.conf /etc/nginx/conf.d/default.conf
RUN         chmod -R 775 entrypoint.sh

ENTRYPOINT	["./entrypoint.sh"]