FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"

# Background on why "mkdir -p /run/nginx" is needed
# https://github.com/gliderlabs/docker-alpine/issues/185
# https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14500

RUN 		mkdir -p /run/nginx

# https://docs.phpmyadmin.net/en/latest/require.html 
# https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7-common
# https://www.php.net/manual/en/libxml.installation.php >> The libxml extension is enabled by default

RUN			apk update && apk upgrade && apk add --no-cache nginx nginx-openrc php-common phpmyadmin 
EXPOSE		5000
ENTRYPOINT	["entrypoint.sh"]