FROM		alpine:ft_services
LABEL       maintainer="Michael Giraldo <mgiraldo@student.42.org>"

# Background on why "mkdir -p /run/nginx" is needed
# https://github.com/gliderlabs/docker-alpine/issues/185
# https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14500
RUN 		mkdir -p /run/nginx

# https://make.wordpress.org/hosting/handbook/handbook/server-environment/
# https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7-common
# https://www.php.net/manual/en/hash.installation.php >> As of PHP 7.4.0, the Hash extension is a core PHP extension, so it is always enabled.
# https://www.php.net/manual/en/pcre.installation.php >> The PCRE extension is a core PHP extension, so it is always enabled

RUN		    apk update && apk upgrade && apk add --no-cache nginx nginx-openrc php-common php7-pecl-imagick 
 
WORKDIR     /usr/share/webapps
ADD		    http://wordpress.org/latest.tar.gz .
RUN		    tar -xzvf latest.tar.gz && rm latest.tar.gz
#RUN         chown -R www-data:www-data wordpress/
RUN		    ln -s /usr/share/wordpress /var/www/localhost/htdocs

EXPOSE		5050

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/wordpress/entrypoint.sh /
COPY        srcs/wordpress/telegraf.conf /etc/telegraf/telegraf.conf
RUN         chmod -R 775 entrypoint.sh

ENTRYPOINT	[./entrypoint.sh"]

# https://github.com/docker-library/wordpress/blob/5125491823651bcd691faf415d836f911fea09cd/php7.4/fpm-alpine/Dockerfile
