FROM		alpine:ft_services
LABEL		maintainer="Michael Giraldo <mgiraldo@student.42.org>"
RUN         mkdir -p /run/proftpd/
RUN			apk update && apk upgrade && apk add --no-cache \
            proftpd proftpd-doc proftpd-mod_tls proftpd-utils perl \
            openssl

RUN          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-subj '/C=US/ST=CALIFORNIA/L=SILICON VALLEY/O=42/CN=HITCHIKERS GUIDE TO PROGRAMMING' \
-keyout /etc/ssl/private/proftpd.key -out /etc/ssl/certs/proftpd.pem

# Alpine Linux uses busybox
# https://busybox.net/downloads/BusyBox.html
# http://linux-training.be/security/ch03.html
RUN         adduser ft_services -D && echo "ft_services:pass" | chpasswd

# Copy configuration files and start up script (entrypoint.sh)
COPY        srcs/ftps/proftpd_tls.conf /etc/proftpd/modules.d/tls.conf
COPY        srcs/ftps/proftpd.conf /etc/proftpd/proftpd.conf 
COPY        srcs/ftps/telegraf.conf /etc/telegraf/telegraf.conf

# Make FTP directory and change ownership
COPY        srcs/ftps/entrypoint.sh /
RUN         chmod -R 775 entrypoint.sh

EXPOSE		20-21 49201-49205

ENTRYPOINT	["./entrypoint.sh"]

#https://github.com/besn0847/ftpd/blob/master/Dockerfile

# https://wiki.alpinelinux.org/wiki/FTPa
# https://github.com/fauria/docker-vsftpd/blob/master/Dockerfile
# https://github.com/onjin/docker-alpine-vsftpd/blob/master/Dockerfile
# https://github.com/fauria/docker-vsftpd/pull/42/files

# https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Upgrade_a_Running_System
# https://pkgs.alpinelinux.org/packages?name=telegraf&branch=edge&arch=x86_64
# https://pkgs.alpinelinux.org/packages?name=vsftpd&branch=edge&arch=x86_64
